# ============================================================================ #
#
# IP-Check v2.0.7 b2084 | RP-Commons v1.1.0 b201 -- Author: Jnk1296
# For more information visit http://dev.bukkit.org/server-mods/ip-check-jnk/
#
# IT IS RECOMMENDED THAT YOU READ THE CONFIGURATION EXPLANATION BEFORE MAKING
# MODIFICATIONS TO ANY OF THESE VALUES.
#
# Configuration Explanation can be found at:
# http://dev.bukkit.org/bukkit-plugins/ip-check-jnk/pages/default-configuration/
#
# This product includes GeoLite data created by MaxMind, available from:
# http://www.maxmind.com/
#
# ============================================================================ #

# Localization Language Selection
# Default language is english if empty or "en".
# To switch language put in the name of the language-file (e.g. "de" for de.yml)
language: "en"

# Use MySQL instead of SQLite?
use-mysql: false

# Login details if backend is mysql
dbUsername: "root"
dbPassword: ""
dbHostname: "127.0.0.1"
dbName: "ip-check"
dbPort: 3306

# Set this to false if you want the tables to be regenerated
dbGenerated: false
